# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='parent_activity',
            new_name='parent',
        ),
    ]
